# -*- coding: utf-8 -*-
"""
Created on Tue Dec  4 16:47:07 2018

@author: ALLAN
"""

import pandas as pd
import itertools
import os
import numpy as np
from maps import Maps

if __name__ == '__main__':
    df = pd.read_csv('metadadosdrogasposicaogeografica2.csv', encoding = "ISO-8859-1", sep=';')
    df.head()
    df['Nome']= df['Nome'].astype(str)

    #df['text'] = df['sample_name'] + '; ' + df['location'] + '; ' + 'Lat: ' + df['Latitude'].astype(str) + '; ' + 'Long: ' + df['Longitude'].astype(str)
    df['text'] = df['Nome'] + '; ' + df['sample_name'] + '; ' + df['Substance'] + '; ' + df['location']
    
    db=df.set_index('Nome').T.to_dict('list')
    
    m = Maps('Drugs in the world','drugs_in_the_world.html')
    
    #######Test plot_all
    m.plot_all(df['Latitude'],df['Longitude'],df['text'])
    m.show_map()
    
    #######Test plot_retrieval
    
    #reading the files that was generated by the image descriptor
    classes = list(itertools.chain(*(pd.read_csv('ilicitas_lenet/labels_cnn_training.csv', sep=',').values.tolist())))
    features = pd.read_csv('ilicitas_lenet/feature_vectors_cnn_training.csv', sep=',').values.tolist()
    im_filenames = list(itertools.chain(*(pd.read_csv('ilicitas_lenet/image_filenames_cnn_training.csv', sep=',').values.tolist())))
    im_filenames = [os.path.basename(item)[:-7] for item in im_filenames]
    
    ##Lost data: "4065"
    db['4065']=[' Mortal Kombat 2', 'MDMA', 'Aug 13, 2013', 'Aug 13, 2013', 'Lanarkshire, Scotland', 55.673, 3.782,'']

    m.plot_retrieval([db[item][5] for item in im_filenames],
                    [db[item][6] for item in im_filenames],
                    [db[item][7] for item in im_filenames], 
                    '3558', classes, features, im_filenames,30)
    m.set_title('Drugs in the world',)
    m.set_result_filename('retrieval_drugs_in_the_world.html')
    m.show_map()
    
    #######Test plot_classes function
    
    colors=np.loadtxt('cores_k99.txt')
    
    m.plot_classes([db[item][5] for item in im_filenames],
                    [db[item][6] for item in im_filenames],
                    [db[item][7] for item in im_filenames], 
                    classes, colors)
    m.set_title('Drugs in the world',)
    m.set_result_filename('classes_of_drugs_in_the_world.html')
    m.show_map()